### ISSUE TITLE
Changing speed of real-time output 

### ISSUE THREAD

**Issue by adamwintle** [unconv/chat-wtf#12]
Hello, in your [YouTube video](https://www.youtube.com/watch?v=lYq6r6jqB1U&t=858s) you adjust the speed of the real-time output, can you please help identify which line of code this is located?

**Comment by unconv** [comment]
If you're referring to [this](https://youtu.be/lYq6r6jqB1U?t=535) part of the video, I was just changing the speed of my test SSE example, not the ChatGPT output. That can't be sped up.

**Comment by unconv** [comment]
It seems like a problem with output buffering. Perhaps you're running it on a server that buffers the output. For me it works with `php -S localhost` and running on a local Apache server. Could you check the Headers tab in the Chrome dev tools? Mine looks like this:

![Screenshot from 2023-06-22 15-57-02](https://github.com/unconv/chat-wtf/assets/120440395/c9517a19-ce83-44f4-8218-2d521705ec8a)

This article might help: https://stackoverflow.com/questions/4706525/php-flush-not-working

Maybe you need to call `ob_flush();` somewhere (everywhere `flush();` is called in `chatgpt.php` and `message.php`. Or perhaps it needs to be `if(ob_get_contents()) {ob_flush();}`

**Comment by unconv** [comment]
@adamwintle Great! If you changed the code to make it work, could you tell what you changed exactly so I could fix it in the repo :)

**Comment by unconv** [comment]
Ok, good to know!
