### ISSUE TITLE
LIMIT 1 produces error

### ISSUE THREAD

**Issue by RobertEcker** [unconv/chat-wtf#13]
hi, cool script - thank you

```
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 near "LIMIT": syntax error in database.php on line 79
PDOException: SQLSTATE[HY000]: General error: 1 near "LIMIT"
```
if I remove "LIMIT 1", it will work (several occurrences)

**Comment by unconv** [comment]
Thanks! I'll update the code. I guess LIMIT is not supported with DELETE in some SQL databases, and in fact it is unnecessary in this case (I like to add it "just in case" for every DELETE that is supposed to delete only one entry). It should work for MySQL and SQLite, though.

**Comment by RobertEcker** [comment]
AFAIK LIMIT is possible with MySQL but not with SQLITE

[MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/delete.html)
[SQLITE stackoverflow](https://stackoverflow.com/questions/1824490/how-do-you-enable-limit-for-delete-in-sqlite)

**Comment by unconv** [comment]
There seems to be a compile time option `SQLITE_ENABLE_UPDATE_DELETE_LIMIT` to enable this in SQLite. Perhaps it's enabled in the `php-sqlite3` package on Ubuntu, since it seems to work fine for me.
