### ISSUE TITLE
Remembering the conversation

### ISSUE THREAD

**Issue by JoaoFOliveira** [unconv/chat-wtf#15]
Hello!

Been following your videos for a while now, being a PHP enthusiast for ages. Great job and keep up the good work :)

While thinking about the need (or lack there of) to send the past message history whenever we send a request to the API, I asked chatGPT the following:

> if i want the api to remember the conversation, do i always have to send the whole past conversation whenever i send a new message?

and this was the response:

> No, you don't have to send the entire past conversation every time you make a request to the OpenAI API if you want the model to remember the conversation context. Instead, you can use a system-level instruction to instruct the model to remember the conversation history. This allows you to send only the new message or messages without repeating the entire conversation.
> 
> Here's an example of how you can use a system-level instruction to instruct the model to remember the conversation (...)

```
"messages": [
    {"role": "system", "content": "You are a helpful assistant that remembers the conversation."},
    {"role": "user", "content": "What's the weather like today?"}
]
```

> In this example, the system instruction tells the model to remember the conversation. Subsequent requests can then include only the new user or assistant messages,

So, wouldn't this be a way to save A LOT of tokens and api usage? just a thought, not a bug report or anything like that.

Best regards from Portugal 👋

**Comment by unconv** [comment]
Hi! Thanks for watching my videos :)

I think ChatGPT is just hallucinating that information or understood your question incorrectly. In reality, you need to send the whole chat history with every request. The history needs to be fed to the LLM anyway, so there's no way around using more tokens with a longer conversation. API requests are not dependent on each other, so there would be nothing to link the API request to a previous one.
