### ISSUE TITLE
Result does not print out in frontend as per chatgpt

### ISSUE THREAD

**Issue by azmunkz** [unconv/chat-wtf#16]
Hi, I have clone the repo and completed the settings. All goes well but the result does not appending like chatGPT. I wait and show the result at one go, not like the typing effect. Is there any settings or additional package/script that need to be added? Thanks.

**Comment by unconv** [comment]
I accidentally broke streaming on the PHP built-in server in 74b7fb3848 when I made the project work for Docker. You can remove the if statement on line 3 of `message.php` so that `ob_end_flush()` is run every time. That should fix the issue. I'll fix this in the repo soon-ish

**Comment by azmunkz** [comment]
Thanks for your swift reply. Great. Thanks a lot.

**Comment by unconv** [comment]
Fixed in 8347d38
