### ISSUE TITLE
Customized Parameters For fine tuned model

### ISSUE THREAD

**Issue by ozarafurkan** [unconv/chat-wtf#17]
Hi,
Ive tried to use that repo for my fine tuned chatgpt model, Ive set the my api key and fine-tuned model name in settings.php.
The client works well but I need to set parameters like while taking response on python  : 

```
  response = openai.ChatCompletion.create(
        model= " ", 
        messages= "", 
        temperature=0.1,  # like this
        max_tokens=200,  # like this
        top_p = 0.9 # like this
    )
```

Is there any way to set that kind of parameters on that repo ? 
Thanks for all :)

**Comment by unconv** [comment]
Hi!

You can now (since 9908ca0) set these custom parameters in the `settings.php` file:

```php
return [
    // ... other settings ...

    // custom parameters for ChatGPT
    "params" => [
        "temperature" => 0.9,
        "max_tokens" => 256,
    ],

    // ... other settings ...
]
```

You can add any parameters that the ChatGPT API allows.

I hope this helps :)
