### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by ctrlvb** [unconv/chat-wtf#2]
I cant run the php

![Screenshot_3](https://user-images.githubusercontent.com/97078505/226547207-f5b9c73e-ef06-4e4e-9aa8-a4e429e3c5dc.jpg)

**Comment by unconv** [comment]
Check the network tab of Chrome dev tools while you send a message. It's probably returning an error message instead of JSON. Also check the PHP error log.

**Comment by ctrlvb** [comment]
this is the error log 
[21-Mar-2023 08:46:52 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/xervir/public_html/chat/message.php:1) in /home/xervir/public_html/chat/message.php on line 10
[21-Mar-2023 08:46:52 UTC] PHP Fatal error:  Uncaught Error: Class "Orhanerday\OpenAi\OpenAi" not found in /home/xervir/public_html/chat/message.php:15
Stack trace:
#0 {main}
  thrown in /home/xervir/public_html/chat/message.php on line 15
  
  What do I missed?

**Comment by unconv** [comment]
The chatbot requires the Composer packages `orhanerday/open-ai` and `league/commonmark`. You need to install these packages by running `composer install` from the terminal when you are in the same folder as the `composer.json` file.

If you're not familiar with Composer, you should search about it first, or ask ChatGPT.

You can find instructions for installing Composer here: https://getcomposer.org/download/

**Comment by ctrlvb** [comment]
solved! by running this 2 command 
aside from installing composer, run this:
composer require orhanerday/open-ai
composer require league/commonmark

**Comment by unconv** [comment]
@richcafcat it should work now with the latest version :)
