### ISSUE TITLE
Stream Responce

### ISSUE THREAD

**Issue by amosmills** [unconv/chat-wtf#21]
Is there a simple way to enable response streaming? Thanks

**Comment by unconv** [comment]
Response streaming is on by default and there's no setting to disable it. If you're not getting streamed responses, something might be wrong with your server config. What's your setup?

**Comment by amosmills** [comment]
PHP 8 + IIS + MySQL. Using gpt-4o-mini but was trying other models earlier.

**Comment by unconv** [comment]
It's probably someting about IIS. I've never used it but ChatGPT suggested the following which you could try:

> IIS often uses FastCGI for PHP, which buffers the entire response before sending it. To disable buffering, edit the FastCGI settings in IIS:
>    - Open IIS Manager, select your server or website, then go to **FastCGI Settings**.
>    - Select the PHP FastCGI application, click **Edit**, and set `Activity Timeout` and `Idle Timeout` to values appropriate for streaming.
>    - Set `Response Buffering Limit` to 0 to allow immediate flushing.

Might also be something about the code since I haven't tested with IIS

**Comment by amosmills** [comment]
Appreciate the help. Will let you know if I find the answer.

**Comment by amosmills** [comment]
Came across these steps, and followed the process to edit the responseBufferLimit to 0. Now working. Thanks for the pointers.

1. On the server main page, under "Management", select "Configuration Editor";
2. under "Section", enter 'system.webServer/handlers';
3. next to "(Collection)" click "..." OR mark the element "(Collection)" and, under "Actions" und '(Collection)' Element, click "Edit Items";
4. scroll down until you find your PHP version under "Name";
5. at the bottom, the Properties are shown an can be edited manually, including responseBufferLimit, which should be set to 0 for flush() to work.

**Comment by unconv** [comment]
Glad you got it to work and thanks for the steps!
