### ISSUE TITLE
message.php error

### ISSUE THREAD

**Issue by chaveamin** [unconv/chat-wtf#4]
I get this error when sending a message in PHP version. is there any dependency I should install?
![1](https://github.com/unconv/chat-wtf/assets/78597787/136948cc-9abb-4d2e-8505-5e458ce7d07d)

**Comment by unconv** [comment]
The error code is 404 which means that the file was not found. The `script.js` sends the message to `/message.php` with a `/` in the beginning so `message.php` needs to be in the document root for it to work. If your `index.php` is at `https://yourdomain.com/chat/index.php` then it won't work. I need to fix this in the future. You can fix it by moving the app to the document root or by removing the `/` from the front of `message.php` on line 29 in `script.js`

**Comment by chaveamin** [comment]
Thanks it solved the error. bu I'm getting error 500 which means **server issues** according to the [docs](https://help.openai.com/en/articles/6891839-api-error-code-guidance) I checked their [status page](https://status.openai.com/) and there is no maintenance
![1](https://github.com/unconv/chat-wtf/assets/78597787/c9a99bf9-efdf-494f-ac53-e8ba3b17307e)

**Comment by unconv** [comment]
Check the PHP error logs to see what the error is, or check the network tab of developer tools, if you have error output on in PHP. This app also requires the `orhanerday/open-ai` composer package to use the ChatGPT API, so make sure you've installed that as well.

**Comment by unconv** [comment]
@chaveamin I just updated the code so that it doesn't depend on the `orhanerday/open-ai` package anymore. You can try it again now to see if it works.

**Comment by chaveamin** [comment]
Thanks, now it works without any errors

**Comment by unconv** [comment]
Good to hear!
