### ISSUE TITLE
Replace using EventSource with mpetazzoni/sse.js

### ISSUE THREAD

**Issue by viraljetani** [unconv/chat-wtf#5]
Hey,

I was checking this and found out that EventSource doesn't support a post method so to use this with a secure form & post data we will need to use a library like sse.js which supports post method and all other goodies that EventSource supports. 

Below is the link to the library I am mentioning:
https://github.com/mpetazzoni/sse.js

I am currently trying to implement a streaming functionality to my existing openAI code and came across this code which is nicely done but needs POST method support. 

Cheers!

**Comment by unconv** [comment]
Thanks for the suggestion, I'll check it out!

I was planning to send a separate POST request to one endpoint that would save the message and then send a request to EventSource which would then stream the response. But this library would make it possible to do that with one request. Pretty cool.

**Comment by unconv** [comment]
@viraljetani I tried the library and it worked, but ultimately I went with my own implementation that sends a POST request with the message content and then listens to the response with EventSource. You can see the video where I implemented it ([here](https://www.youtube.com/watch?v=Hbhm0ym45Ug))
